# @package _global_

defaults:
  - _self_
  - data: dummy # choose datamodule with `test_dataloader()` for evaluation
  - energy: gmm
  - model: dem
  - launcher: null
  - logger: tensorboard
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

  - experiment: gmm_idem

task_name: "eval"

tags: ["dev"]
test_mode: 'test' # test or test_oracle
num_estimator_mc_samples: 1000

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
